[bumpver]
current_version = "1.2.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit = false
tag = false

[bumpver.file_patterns]
"pyproject.toml" = [
	'version = "{version}"'
]
"leetcrate/generators/__init__.py" = [
	'__version__ = "{version}"'
]
"leetcrate/__init__.py" = [
	'__version__ = "{version}"'
]
"bumpver.toml" = [
	'current_version = "{version}"'
]




# usage:
#before that updateing, run:
#.venv\Scripts\activate

# 0.0.x:
# bumpver update --patch

# 0.x.0:
# bumpver update --minor

# x.0.0:
# bumpver update --major