# LeetCode Problem Generator - Settings

[LeetCode Problem Generator]
# Available languages: python, java, javascript, go, cpp
language = python

[Framework]
contests = false
courses = false
interview = false
